package edu.usc.softarch.arcade.frontend.arghandlers;

import java.io.FileNotFoundException;
import java.io.File;
import java.io.IOException;

/**
 * Argument Handler  for the path to a directory Code-maat csv file.
 * *_clean.csv
 *
 * @author Khoi
 */
public class CleanUpCodeMaatFile
  extends ArgHandler
{
  //#region ATTRIBUTES
  private static ArgHandler cleanUpCodeMaatFile;
  //#endregion

  //#region CONSTRUCTORS
  private CleanUpCodeMaatFile()
  {
    String name = "cleanUpCodeMaatFile";
    String description = "Clean Up Code Maat File";
    String instruction = "Clean Up Code Maat File: This is a file generated by cleanUpCodeMaat.java";
    instruction += "usually of the form ";
    instruction += "*_clean.csv.";

    initialize(name, description, instruction);
  }

  public static ArgHandler getInstance()
  {
    if(cleanUpCodeMaatFile == null) cleanUpCodeMaatFile = new CleanUpCodeMaatFile();
    return cleanUpCodeMaatFile;
  }
  //#endregion

  //#region VALIDATION
  @Override
  public boolean validateAsInput(String value)
    throws Exception
  {
    File cleanUpCodeMaatFile = new File(value);
    if(!cleanUpCodeMaatFile.exists())
      throw new FileNotFoundException(value + " not found.");
    else if ((value.length() < 10) 
			|| !(value.substring(value.length()-10).equals("_clean.csv"))) 
			{		      
		      throw new IllegalArgumentException(value + "Invalid file type (must be _clean.csv file)" );
		    }	   

    return true;
  }

  @Override
  public boolean validateAsOutput(String value)
  {
    return true;
  }
 
  //#endregion
}