package edu.usc.softarch.arcade.frontend.arghandlers;

import java.io.File;

/**
 * Argument Handler for the path to a Cluster File, which contains cluster
 * data obtained by an architectural recovery technique. Not to be confused with
 * {@link ClusterDir}.
 *
 * @author Marcelo Schmitt Laser
 */
public class ClusterFile
  extends ArgHandler
{
  //#region ATTRIBUTES
  private static ArgHandler clusterFile;
  //#endregion

  //#region CONSTRUCTORS
  private ClusterFile()
  {
    String name = "clusterFile";
    String description = "Cluster File";
    String instruction = "This is a file generated by an architectural ";
    instruction += "recovery technique, containing cluster data. Typically in ";
    instruction += ".rsf format.";

    initialize(name, description, instruction);
  }

  public static ArgHandler getInstance()
  {
    if(clusterFile == null) clusterFile = new ClusterFile();
    return clusterFile;
  }
  //#endregion

  //#region VALIDATION
  @Override
  public boolean validateAsInput(String value)
    throws Exception
  {
    File clusterFileVar = new File(value);
    if(!clusterFileVar.exists())
      throw new Exception("Cluster file not found at given path: " + value);
    return true;
  }

  @Override
  public boolean validateAsOutput(String value)
    throws Exception
  {
    File clusterFileVar = new File(value);
    if (!clusterFileVar.getParentFile().exists()
      && !clusterFileVar.getParentFile().mkdirs())
        throw new Exception("Failed to create cluster directory.");
    return true;
  }
  //#endregion
}
