package edu.usc.softarch.arcade.frontend.arghandlers;

import java.io.FileNotFoundException;
import java.io.File;
import java.io.IOException;

/**
 * Argument Handler for the path of a Dependencies RSF file, typically of the
 * form *_deps.rsf.
 *
 * @author Marcelo Schmitt Laser
 */
public class DepsRsfFile
  extends ArgHandler
{
  //#region ATTRIBUTES
  private static ArgHandler depsRsfFile;
  //#endregion

  //#region CONSTRUCTORS
  private DepsRsfFile()
  {
    String name = "depsRsfFile";
    String description = "Dependencies RSF file";
    String instruction = "Dependencies RSF file: This is a file generated by ";
    instruction += "a dependency builder, usually of the form *_deps.rsf.";

    initialize(name, description, instruction);
  }

  public static ArgHandler getInstance()
  {
    if(depsRsfFile == null) depsRsfFile = new DepsRsfFile();
    return depsRsfFile;
  }
  //#endregion

  //#region VALIDATION
  @Override
  public boolean validateAsInput(String value)
    throws FileNotFoundException
  {
    File depsRsfFile = new File(value);
    if(!depsRsfFile.exists())
      throw new FileNotFoundException(value + " not found.");

    return true;
  }

  @Override
  public boolean validateAsOutput(String value)
    throws IOException
  {
    File depsRsfFile = new File(value);
    if(!depsRsfFile.getParentFile().exists()
      && !depsRsfFile.getParentFile().mkdirs())
        throw new IOException("Failed to create output directory.");

    return true;
  }
  //#endregion
}
