package edu.usc.softarch.arcade.frontend.arghandlers;

import java.io.File;
import java.io.IOException;

public class InferenceFile
  extends ArgHandler
{
  //#region ATTRIBUTES
  private static ArgHandler inferenceFile;
  //#endregion

  //#region CONSTRUCTORS
  private InferenceFile()
  {
    String name = "inferenceFile";
    String description = "Inference File";
    String instruction = "This is the path to an infer.mallet file that is ";
    instruction += "generated by mallet.";

    initialize(name, description, instruction);
  }

  public static ArgHandler getInstance()
  {
    if(inferenceFile == null) inferenceFile = new InferenceFile();
    return inferenceFile;
  }
  //#endregion

  //#region VALIDATION
  @Override
  public boolean validate(String value)
    throws Exception
  {
    File arcBaseDir = new File(value);
    if(!arcBaseDir.exists() && !arcBaseDir.mkdirs())
      throw new IOException("Failed to create output directory.");

    return true;
  }
  //#endregion
}
