package edu.usc.softarch.arcade.frontend.arghandlers;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;

/**
 * PkgPrefixes for the pkg clustering output
 * generated by batchpakager.py
 *
 * @author Khoi
 * see edu.usc.softarch.arcade.frontend.tooladapters.pkg.batchpackagerWrapper
 */

public class PkgPrefixes
  extends ArgHandler
{
  //#region ATTRIBUTES
  private static ArgHandler pkgprefixes;
  //#endregion

  //#region CONSTRUCTORS
  private PkgPrefixes()
  {
    String name = "pkgPrefixes";
    String description = "pkg Prefixes";
    String instruction = "This is the package prefixes";
    instruction += "generated by batchpakager.py";

    initialize(name, description, instruction);
  }

  public static ArgHandler getInstance()
  {
    if(pkgprefixes == null) pkgprefixes = new PkgPrefixes();
    return pkgprefixes;
  }
  //#endregion

  //#region VALIDATION
  @Override
  public boolean validateAsInput(String value)
    throws Exception
  {	  

	  return true;
  }

  @Override
  public boolean validateAsOutput(String value)
    throws Exception
  {

    return true;
  }   

  //#endregion
}