package edu.usc.softarch.arcade.frontend.arghandlers;

import java.io.FileNotFoundException;
import java.io.File;
import java.io.IOException;

/**
 * Argument Handler for the path of a Project.log file, typically of the form
 * *project.log.
 *
 * @author Khoi
 */
public class ProjectLogFile
  extends ArgHandler
{
  //#region ATTRIBUTES
  private static ArgHandler projectLogFile;
  //#endregion

  //#region CONSTRUCTORS
  private ProjectLogFile()
  {
    String name = "projectLogFile";
    String description = "Project.log File";
    String instruction = "Project.log file: This is a file generated by ";
    instruction += "git log command in a specific project local repo (with .git folder)";
    instruction += "usually named: project.log.";

    initialize(name, description, instruction);
  }

  public static ArgHandler getInstance()
  {
    if(projectLogFile == null) projectLogFile = new ProjectLogFile();
    return projectLogFile;
  }
  //#endregion

  //#region VALIDATION
  @Override
  public boolean validateAsInput(String value)
    throws Exception
  {
    File projectLogFile = new File(value);
    if(!projectLogFile.exists())
      throw new FileNotFoundException(value + " not found.");
    else if ((value.length() < 4) 
			|| !(value.substring(value.length()-4).equals(".log"))) 
			{		      
		      throw new IllegalArgumentException(value + "Invalid file type (must be .log file)" );
		    }	   

    return true;
  }

  @Override
  public boolean validateAsOutput(String value)
    throws Exception
  {
//    File projectLogFile = new File(value);
//    if (!projectLogFile.getParentFile().exists()
//      && !projectLogFile.getParentFile().mkdirs())
//        throw new IOException("Failed to create Cluster .ser output directory.");

    return true;
  }
 
  //#endregion
}
