package edu.usc.softarch.arcade.frontend.arghandlers;

public class SmellsFile
  extends ArgHandler
{
  //#region ATTRIBUTES
  private static ArgHandler smellsFile;
  //#endregion

  //#region CONSTRUCTORS
  private SmellsFile()
  {
    String name = "smellsFile";
    String description = "Smells SER File";
    String instruction = "Smells SER File: This is a file generated by a smell";
    instruction += " detection technique, usually of the form *_smells.ser.";

    initialize(name, description, instruction);
  }

  public static ArgHandler getInstance()
  {
    if(smellsFile == null) smellsFile = new SmellsFile();
    return smellsFile;
  }
  //#endregion

  //#region VALIDATION
  @Override
  public boolean validate(String value)
    throws Exception
  {
    //TODO
    return true;
  }
  //#endregion
}
