package edu.usc.softarch.arcade.frontend.console.mallet;

import org.apache.commons.lang3.SystemUtils;
import java.util.Map;
import java.util.HashMap;
import edu.usc.softarch.arcade.frontend.console.ConsoleUI;
import edu.usc.softarch.arcade.frontend.console.Console;
import edu.usc.softarch.arcade.frontend.tooladapters.ToolAdapter;
import edu.usc.softarch.arcade.frontend.tooladapters.mallet.Inferencer;

public class InferencerConsoleUI
  extends ConsoleUI
{
  ToolAdapter inferencer = new Inferencer(false);

  @Override
  public String getName()
  {
    return "inferencer";
  }

  @Override
  public String getMessage()
  {
    return "Mallet: Inferencer";
  }

  @Override
  public String getInstructions()
  {
    String cr = System.lineSeparator();
    String instructions = "Mallet's inference requires the following ";
    instructions += "arguments:" + cr;
    instructions += "Input: This is the path to the topicmodel.data file ";
    instructions += "generated by Mallet's topic model generator. " + cr;
    instructions += "Output Directory: This is the directory where the output ";
    instructions += "file goes." + cr;
    instructions += "Tool path: path to mallet's executable (mallet for Linux ";
    instructions += "or mallet.bat for Windows)";

    return instructions;
  }

  @Override
  public Map<String,String> loadArgumentsWizard()
  {
    //TODO this is atrocious and unreadable, fix it
    if(SystemUtils.IS_OS_WINDOWS)
    {
      System.out.print("Arcade has detected that you are executing from a ");
      System.out.println("Windows OS machine.");
      Map<String,String> environment = new HashMap<String,String>();

      if(Console.arguments.containsKey("malletHome"))
      {
        System.out.print("Argument malletHome found in configuration. ");
        System.out.println("Use existing configuration? (y/n)");
        String choice = Console.in.nextLine();
        if(choice.equals("y"))
          environment.put("MALLET_HOME", Console.arguments.get("malletHome"));
      }

      if(!environment.containsKey("MALLET_HOME"))
      {
        System.out.print("Please enter the path to Mallet's home directory in");
        System.out.println("order to set a temporary environment variable:");
        String malletHome = Console.in.nextLine();
        environment.put("MALLET_HOME", malletHome);
        Console.arguments.put("malletHome", malletHome);
      }

      inferencer.setEnvironment(environment);
    }

    // Use existing config
    if(Console.arguments.containsKey("topicModel")
      && Console.arguments.containsKey("arcOutput")
      && Console.arguments.containsKey("malletPath"))
    {
      System.out.print("All arguments found in configuration. ");
      System.out.println("Use existing arguments? (y/n)");
      String choice = Console.in.nextLine();
      if(choice.equals("y"))
      {
        inferencer.setToolPath(Console.arguments.get("malletPath"));
        return Console.arguments;
      }
    }

    Map<String,String> result = new HashMap<String,String>();

    if(Console.arguments.containsKey("topicModel"))
    {
      System.out.print("Argument topicModel found in configuration. ");
      System.out.println("Use existing configuration? (y/n)");
      String choice = Console.in.nextLine();
      if(choice.equals("y"))
        result.put("topicModel", Console.arguments.get("topicModel"));
    }

    if(!result.containsKey("topicModel"))
    {
      System.out.println("Please enter path to topicmodel.data: ");
      String topicModel = Console.in.nextLine();
      result.put("topicModel", topicModel);
      Console.arguments.put("topicModel", topicModel);
    }

    if(Console.arguments.containsKey("arcOutput"))
    {
      System.out.print("Argument arcOutput found in configuration. ");
      System.out.println("Use existing configuration? (y/n)");
      String choice = Console.in.nextLine();
      if(choice.equals("y"))
        result.put("arcOutput", Console.arguments.get("arcOutput"));
    }

    if(!result.containsKey("arcOutput"))
    {
      System.out.println("Please enter output directory: ");
      String arcOutput = Console.in.nextLine();
      result.put("arcOutput", arcOutput);
      Console.arguments.put("arcOutput", arcOutput);
    }

    boolean pathSet = false;

    if(Console.arguments.containsKey("malletPath"))
    {
      System.out.print("Argument malletPath found in configuration. ");
      System.out.println("Use existing configuration? (y/n)");
      String choice = Console.in.nextLine();
      if(choice.equals("y"))
      {
        inferencer.setToolPath(Console.arguments.get("malletPath"));
        pathSet = true;
      }
    }

    if(!pathSet)
    {
      System.out.println("Please enter path to mallet's executable: ");
      String malletPath = Console.in.nextLine();
      inferencer.setToolPath(Console.arguments.get("malletPath"));
      Console.arguments.put("malletPath", malletPath);
    }

    return result;
  }

  @Override
  public void execute(Map<String,String> args)
    throws Exception
  {
    inferencer.addArguments(args);
    inferencer.execute();
  }

  @Override
  public String[] loadRequisites()
  {
    return new String[]{ "pipeextractor", "topicmodelgenerator" };
  }
}
